[package]
name = "demo_072020"
version = "0.1.0"
authors = ["RussellBentley <russell.w.bentley@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.2.7"
noise = "0.6.0"
