version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest

jobs:
  checkout:
    executor: rust-executor
    steps:
      - checkout

  check-fmt:
    executor: rust-executor
    steps:
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: check formatting
          command: cargo fmt -- --check

  build-web:
    executor: rust-executor
    steps:
      - run:
          name: build web 
          command: ./build_web.sh
      
workflows:
  version: 2
  build:
    jobs:
      - checkout
      - check-fmt:
          requires:
            - checkout
      - build-wasm:
          require:
            - checkout
