version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest

jobs:
  build-web:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: install wasm32-unknown-unknown
          command: rustup target add wasm32-unknown-unknown
      - run:
          name: check formatting
          command: cargo fmt -- --check
      - run:
          name: build web 
          command: ./build_web.sh
      - store_artifacts:
          path: ~/project/target/web
          destination: web 
      
workflows:
  version: 2
  build:
    jobs:
      - build-web
